import './components/template.js'
import './components/bindings/text.js'
import './components/bindings/attribute.js'
import './components/bindings/property.js'
import './components/bindings/events.js'
import './components/bindings/node.js'
import './components/bindings/template.js'
import './components/bindings/templateMap.js'
